name: New Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Plugin Data
        uses: actions/checkout@v1
      - name: Installing Composer
        uses: pxgamer/composer-action@master
        with:
          command: install --no-dev
      - name: WordPress Plugin Deploy
        uses: varunsridharan/action-wp-org-deploy@master
        with:
          WORDPRESS_PASSWORD: ${{ secrets.WP_PASSWORD }}
          WORDPRESS_USERNAME: ${{ secrets.WP_USERNAME }}
          SLUG: ${{ secrets.WP_SLUG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
